monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.pci-.*"
        device.vendor.id = "0x1022"
        device.product.id = "0x15e3"
      }
    ]
    actions = {
      update-props = {
        device.profile-set = "px13.conf"
        api.alsa.use-ucm = false
      }
    }
  }
]
