[General]
priority = 89
description = Internal Microphone
type = mic

[Element Capture]
switch = mute
volume = merge
override-map.1 = all
override-map.2 = all-left,all-right

[Element Internal Mic]
switch = off

[Element Internal Mic Boost]
volume = zero

[Element Internal Mic 1]
required = switch
switch = mute

[Element Internal Mic Boost,1]
volume = zero

.include analog-input-mic.conf.common
